GET http://localhost:3000/

###

GET http://localhost:3000/api/dog

###

GET http://localhost:3000/api/dog/1

###

POST http://localhost:3000/api/dog
Content-Type: application/json

{
    "name": "B",
    "breed": "none",
    "age": 4
}

###

PATCH  http://localhost:3000/api/dog/1
Content-Type: application/json

{
    "name": "Vally",
    "age": 8
}

###

DELETE  http://localhost:3000/api/dog/1

###
